### PR TITLE
any node lang attribute + consider html lang='..' as a fallback

### PR DESCRIPTION
**Pull request by Hexagon**
Proposed changed related to issue #1 
* Consider node lang=".."
* Consider html lang=".." as a fallback to body lang=".." 

(More info: https://www.w3.org/International/questions/qa-html-language-declarations)

### CODE REVIEW

**Comment by Hexagon** [comment]
Thoughts on this?

**Comment by brocococonut** [comment]
It looks good to me!
Sorry for the delay - been busy over the holidays.

Would you be able to rebase your commit onto main again? The main changes are that the preact types were moved from shared.ts to mod.ts and running deno fmt.

Really appreciate the PR btw!

Also, once you update the pr, I'll merge it and likely split off the translation service class and the Fresh wrapper so people can use the class separately. So there'll exist a `freshlate` (open to alternative names) repo and a `[repo]-fresh` repository

**Comment by Hexagon** [comment]
Cool! I'm in no hurry - i just vendored the modified version of freshlate in my project (https://github.com/Hexagon/spotweb) while i'm waiting :) 

Anyways, rebased and ready now!

**Comment by brocococonut** [comment]
I'll go ahead and accept this, then update the mod.ts to have the lang property

**Pull request merged**
